apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-billing-config
  namespace: oficina
data:
  DB_URL: "jdbc:postgresql://postgres-billing:5433/oficina_billing"
  DB_USER: "oficina"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  KEYCLOAK_ISSUER: "http://keycloak:8080/realms/oficina"
