apiVersion: v1
kind: Secret
metadata:
  name: oficina-billing-secrets
  namespace: oficina
type: Opaque
stringData:
  DB_PASS: "CHANGE_ME"
  RABBITMQ_PASS: "CHANGE_ME"
  MERCADOPAGO_TOKEN: "CHANGE_ME"
